NATIVE_FUNCTION_HEAD(GLuint,glCreateProgram,void) NATIVE_FUNCTION_VALUE(GLuint,glCreateProgram,);
NATIVE_FUNCTION_HEAD(void,glDeleteProgram,GLuint program) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glDeleteProgram,program);
NATIVE_FUNCTION_HEAD(void,glGetProgramiv,GLuint program, GLenum pname, GLint *params) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramiv,program,pname,params);
NATIVE_FUNCTION_HEAD(void,glGetProgramInfoLog,GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramInfoLog,program,bufSize,length,infoLog);
NATIVE_FUNCTION_HEAD(GLboolean,glIsProgram,GLuint program) NATIVE_FUNCTION_VALUE(GLboolean,glIsProgram,program);
NATIVE_FUNCTION_HEAD(void,glLinkProgram,GLuint program) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glLinkProgram,program);
NATIVE_FUNCTION_HEAD(void,glUseProgram,GLuint program) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glUseProgram,program);
NATIVE_FUNCTION_HEAD(void,glValidateProgram,GLuint program) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glValidateProgram,program);
NATIVE_FUNCTION_HEAD(void,glGetProgramBinary,GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramBinary,program,bufSize,length,binaryFormat,binary);
NATIVE_FUNCTION_HEAD(void,glProgramBinary,GLuint program, GLenum binaryFormat, const void *binary, GLsizei length) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramBinary,program,binaryFormat,binary,length);
NATIVE_FUNCTION_HEAD(void,glProgramParameteri,GLuint program, GLenum pname, GLint value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramParameteri,program,pname,value);
NATIVE_FUNCTION_HEAD(void,glGetProgramInterfaceiv,GLuint program, GLenum programInterface, GLenum pname, GLint *params) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramInterfaceiv,program,programInterface,pname,params);
NATIVE_FUNCTION_HEAD(GLuint,glGetProgramResourceIndex,GLuint program, GLenum programInterface, const GLchar *name) NATIVE_FUNCTION_VALUE(GLuint,glGetProgramResourceIndex,program,programInterface,name);
NATIVE_FUNCTION_HEAD(void,glGetProgramResourceName,GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramResourceName,program,programInterface,index,bufSize,length,name);
NATIVE_FUNCTION_HEAD(void,glGetProgramResourceiv,GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramResourceiv,program,programInterface,index,propCount,props,bufSize,length,params);
NATIVE_FUNCTION_HEAD(GLint,glGetProgramResourceLocation,GLuint program, GLenum programInterface, const GLchar *name) NATIVE_FUNCTION_VALUE(GLint,glGetProgramResourceLocation,program,programInterface,name);
NATIVE_FUNCTION_HEAD(void,glUseProgramStages,GLuint pipeline, GLbitfield stages, GLuint program) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glUseProgramStages,pipeline,stages,program);
NATIVE_FUNCTION_HEAD(void,glActiveShaderProgram,GLuint pipeline, GLuint program) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glActiveShaderProgram,pipeline,program);
NATIVE_FUNCTION_HEAD(GLuint,glCreateShaderProgramv,GLenum type, GLsizei count, const GLchar *const*strings) NATIVE_FUNCTION_VALUE(GLuint,glCreateShaderProgramv,type,count,strings);
NATIVE_FUNCTION_HEAD(void,glBindProgramPipeline,GLuint pipeline) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glBindProgramPipeline,pipeline);
NATIVE_FUNCTION_HEAD(void,glDeleteProgramPipelines,GLsizei n, const GLuint *pipelines) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glDeleteProgramPipelines,n,pipelines);
NATIVE_FUNCTION_HEAD(void,glGenProgramPipelines,GLsizei n, GLuint *pipelines) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGenProgramPipelines,n,pipelines);
NATIVE_FUNCTION_HEAD(GLboolean,glIsProgramPipeline,GLuint pipeline) NATIVE_FUNCTION_VALUE(GLboolean,glIsProgramPipeline,pipeline);
NATIVE_FUNCTION_HEAD(void,glGetProgramPipelineiv,GLuint pipeline, GLenum pname, GLint *params) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramPipelineiv,pipeline,pname,params);
NATIVE_FUNCTION_HEAD(void,glProgramUniform1i,GLuint program, GLint location, GLint v0) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform1i,program,location,v0);
NATIVE_FUNCTION_HEAD(void,glProgramUniform2i,GLuint program, GLint location, GLint v0, GLint v1) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform2i,program,location,v0,v1);
NATIVE_FUNCTION_HEAD(void,glProgramUniform3i,GLuint program, GLint location, GLint v0, GLint v1, GLint v2) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform3i,program,location,v0,v1,v2);
NATIVE_FUNCTION_HEAD(void,glProgramUniform4i,GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform4i,program,location,v0,v1,v2,v3);
NATIVE_FUNCTION_HEAD(void,glProgramUniform1ui,GLuint program, GLint location, GLuint v0) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform1ui,program,location,v0);
NATIVE_FUNCTION_HEAD(void,glProgramUniform2ui,GLuint program, GLint location, GLuint v0, GLuint v1) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform2ui,program,location,v0,v1);
NATIVE_FUNCTION_HEAD(void,glProgramUniform3ui,GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform3ui,program,location,v0,v1,v2);
NATIVE_FUNCTION_HEAD(void,glProgramUniform4ui,GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform4ui,program,location,v0,v1,v2,v3);
NATIVE_FUNCTION_HEAD(void,glProgramUniform1f,GLuint program, GLint location, GLfloat v0) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform1f,program,location,v0);
NATIVE_FUNCTION_HEAD(void,glProgramUniform2f,GLuint program, GLint location, GLfloat v0, GLfloat v1) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform2f,program,location,v0,v1);
NATIVE_FUNCTION_HEAD(void,glProgramUniform3f,GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform3f,program,location,v0,v1,v2);
NATIVE_FUNCTION_HEAD(void,glProgramUniform4f,GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform4f,program,location,v0,v1,v2,v3);
NATIVE_FUNCTION_HEAD(void,glProgramUniform1iv,GLuint program, GLint location, GLsizei count, const GLint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform1iv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform2iv,GLuint program, GLint location, GLsizei count, const GLint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform2iv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform3iv,GLuint program, GLint location, GLsizei count, const GLint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform3iv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform4iv,GLuint program, GLint location, GLsizei count, const GLint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform4iv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform1uiv,GLuint program, GLint location, GLsizei count, const GLuint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform1uiv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform2uiv,GLuint program, GLint location, GLsizei count, const GLuint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform2uiv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform3uiv,GLuint program, GLint location, GLsizei count, const GLuint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform3uiv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform4uiv,GLuint program, GLint location, GLsizei count, const GLuint *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform4uiv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform1fv,GLuint program, GLint location, GLsizei count, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform1fv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform2fv,GLuint program, GLint location, GLsizei count, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform2fv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform3fv,GLuint program, GLint location, GLsizei count, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform3fv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniform4fv,GLuint program, GLint location, GLsizei count, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniform4fv,program,location,count,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix2fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix2fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix3fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix3fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix4fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix4fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix2x3fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix2x3fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix3x2fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix3x2fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix2x4fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix2x4fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix4x2fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix4x2fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix3x4fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix3x4fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glProgramUniformMatrix4x3fv,GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glProgramUniformMatrix4x3fv,program,location,count,transpose,value);
NATIVE_FUNCTION_HEAD(void,glValidateProgramPipeline,GLuint pipeline) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glValidateProgramPipeline,pipeline);
NATIVE_FUNCTION_HEAD(void,glGetProgramPipelineInfoLog,GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog) NATIVE_FUNCTION_VALUE_NO_RETURN(void,glGetProgramPipelineInfoLog,pipeline,bufSize,length,infoLog);
