name: Build MobileGlues
on: [push, workflow_dispatch]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Navigate to CPP directory
        run: cd src/main/cpp 
      - name: Build MobileGlues
        run: |
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake \
            -DSTATICLIB=OFF \
            -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target mobileglues
      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: MobileGlues-iOS
          path: src/main/cpp/build/RelWithDebInfo/libGL.dylib
